In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing

In [2]:
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [3]:
feature_names = housing['feature_names']
feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [4]:
data = housing['data']
data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]], shape=(20640, 8))

In [5]:
target = housing ['target']
target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,))

In [6]:
df = pd.DataFrame(data= data, columns=feature_names)
x = df
x

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [7]:
df['Target'] = target
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [8]:
df.shape

(20640, 9)

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,target , test_size=0.1, random_state=1)

In [10]:
X_train

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
5425,4.9676,34.0,5.430993,1.075061,973.0,2.355932,34.02,-118.42,4.14100
12499,3.1583,52.0,5.364238,1.139073,326.0,2.158940,38.57,-121.46,1.40000
7020,2.9922,35.0,4.719844,1.029183,2010.0,3.910506,33.97,-118.10,1.63500
6477,3.7066,32.0,4.279627,0.956059,2316.0,3.083888,34.09,-118.08,2.06800
8670,4.5687,32.0,4.622332,0.996716,1338.0,2.197044,33.82,-118.37,3.81200
...,...,...,...,...,...,...,...,...,...
10955,1.7823,17.0,4.055046,1.087156,1079.0,2.474771,33.76,-117.88,2.05300
17289,8.5608,42.0,6.788462,1.011538,753.0,2.896154,34.42,-119.63,5.00001
5192,1.1326,42.0,4.890785,1.006826,775.0,2.645051,33.93,-118.26,1.04800
12172,2.6322,10.0,4.991614,0.951782,1323.0,2.773585,33.73,-117.16,1.40700
235,2.3036,35.0,4.620513,1.176923,1009.0,2.587179,37.79,-122.20,1.26000

In [11]:
X_test

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Target
4712,3.2500,39.0,4.503205,1.073718,1109.0,1.777244,34.06,-118.36,3.550
2151,1.9784,37.0,4.988584,1.038813,1143.0,2.609589,36.78,-119.78,0.707
15927,4.0132,46.0,4.480296,1.012315,1534.0,3.778325,37.73,-122.42,2.294
82,1.5208,52.0,3.908046,1.114943,200.0,2.298851,37.81,-122.28,1.125
8161,5.1795,37.0,5.406360,1.024735,711.0,2.512367,33.82,-118.13,2.254
...,...,...,...,...,...,...,...,...,...
8567,4.5743,28.0,4.881230,1.053022,2191.0,2.323436,33.93,-118.42,3.822
17969,3.6990,19.0,3.532110,1.073394,2672.0,2.042813,37.32,-121.97,2.375
12376,4.0360,5.0,13.885901,2.851017,2880.0,2.093023,33.75,-116.33,1.585
8019,3.7813,36.0,6.634615,1.048077,316.0,3.038462,33.84,-118.10,2.091
13061,4.0938,29.0,5.721973,1.008969,600.0,2.690583,38.60,-121.29,1.091

In [12]:
y_train

array([4.141, 1.4  , 1.635, ..., 1.048, 1.407, 1.26 ], shape=(18576,))

In [13]:
y_test

array([3.55 , 0.707, 2.294, ..., 1.585, 2.091, 1.091], shape=(2064,))

In [14]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [15]:
lr.score(X_train, y_train)

1.0

In [16]:
lr.score(X_test,y_test)

1.0

In [17]:
from sklearn.ensemble import RandomForestRegressor
rfg = RandomForestRegressor(n_estimators=11)
rfg.fit(X_train,y_train)

RandomForestRegressor(n_estimators=11)

In [18]:
rfg.score(X_train, y_train)

0.999999914198802

In [19]:
rfg.score(X_test,y_test)

0.9999997404474775

In [20]:
rfg.predict([[8.32,41.0,6.98,1.023,322.0,2.55,37.88,-122.23]])

C:\Users\Abdul\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

ValueError: X has 8 features, but RandomForestRegressor is expecting 9 features as input.

In [ ]:
rfg.predict([[8.32,41.0,6.98,1.023,322.0,2.55,37.88,-122.23]])

In [ ]:
import pickle
pickle.dump(rfg, open('regressor.pkl', 'wb'))

In [ ]:
model = pickle.load(open('regressor.pkl','rb'))

In [ ]:
model.predict([[8.32,41.0,6.98,1.023,322.0,2.55,37.88,-122.23]])

In [ ]:
{
  "MedInc": 8.3252,
  "HouseAge": 41,
  "AveRooms": 6.984127,
  "AveBedrms": 1.023810,
  "Population": 322,
  "AveOccup": 2.555556,
  "Latitude": 37.88,
  "Longitude": -122.23
}